### ISSUE TITLE
Typo in the Resources Section

### ISSUE THREAD

**Issue by danjkim21** [curtisbarnard/BANKI#2]
Hey there! I noticed a small issue with a link in the Resources Section:

The link for "https://github.com/yangshun/front-end-interview-handbook" links to:
Current: "https://github.com/yangshun/front-end-int- erview-handbook" 
Fix to: "https://github.com/yangshun/front-end-interview-handbook"

See attached image for issue. I'll submit a pull request shortly. Hope this helps!

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/29828039/169163121-28a13f98-0202-4c5e-9a44-603bb7c103eb.png">

**Comment by curtisbarnard** [comment]
Closed with PR #3 thanks!
