### ISSUE TITLE
Code Example Fix and Small Typo

### ISSUE THREAD

**Issue by boonaki** [curtisbarnard/BANKI#21]
Heya, I was playing around with the code given in the example for the question "Explain how prototypal inheritance works " and found that it has a bug. 'this.name' in the greet function returns undefined,  what works though is 'Parent.name'. Have been looking for a reason why that is but no luck.

Also, there are a few comma's in the 'Explanation' part of the answer.

Example Code Given:
```
function Parent() {
  this.name = 'Parent';
}
Parent.prototype.greet = function () {
  console.log('Hello from ' + this.name);
};
const child = Object.create(Parent.prototype);
child.cry = function () {
  console.log('waaaaaahhhh!');
};
child.cry();
// waaaaaahhhh!
child.greet();
// hello from Parent
child.constructor;
// ƒ Parent() {
// this.name = 'Parent';
// }
child.constructor.name;
// 'Parent'
```
This works:
```
Parent.prototype.greet = function () {
  console.log('Hello from ' + Parent.name);
};
```

**Comment by curtisbarnard** [comment]
Thanks for submitting!

Fixed with PR #22
