### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by brendondsouza** [curtisbarnard/BANKI#4]
typo in the answers  file 

Question 2:   Tell me about a time you had to work on several projects at once. How did you handle this?
Cause: I was working on two large projects for two separate clients that were at different stages of their lifecycle. One project was in production and the other project was in the implementation phase.
Action: I decided to send a less experienced colleague to the installation site while I went to do a production check-in on the other project in China. Prior to leaving I briefed my colleague in on the project and told **_then_** what to look out for.

**Comment by curtisbarnard** [comment]
solved with PR #5
