### ISSUE TITLE
HTML-11 Incorrect information

### ISSUE THREAD

**Issue by inherentspice** [curtisbarnard/BANKI#40]
Currently the answer reads: "Yes, I have used EJS. The popular templating languages include Ejs, Jade, Pug, Mustache, HandlebarsJS, Jinja2, and Blade."

However, Jade and Pug are the same templating language. Jade was renamed to Pug.

**Comment by curtisbarnard** [comment]
Thank you. Could you put together a PR?

**Comment by eleanorlatus** [comment]
I'm happy to do this one
