### ISSUE TITLE
typo in the `why use node.js` answer

### ISSUE THREAD

**Issue by victoriacheng15** [curtisbarnard/BANKI#42]
should be `package` instead of `pacakge`

https://github.com/curtisbarnard/BANKI/blob/ceffcca5f66d656e9b99e259a5b5fcc25719e799/BANKI-answers.md?plain=1#L1325

**Comment by curtisbarnard** [comment]
Thanks for finding that. Could you put together a PR?

**Comment by victoriacheng15** [comment]
sure!
